[global]
; Log to stderr
error_log = /dev/stderr

[www]
; The address on which to accept FastCGI requests.
listen = 127.0.0.1:9000

; Specify the user and group that PHP-FPM will run as
; You can use 'www-data' for common web servers or 'root' if necessary
user = nobody
group = nobody

; Enable status page
pm.status_path = /fpm-status

; Ondemand process manager
pm = ondemand

pm.max_children = 200
pm.process_idle_timeout = 10s;
pm.max_requests = 1000

clear_env = no
catch_workers_output = yes
decorate_workers_output = no
ping.path = /fpm-ping