FROM nginx:1.27-alpine

# Remove the default config
RUN rm -f /etc/nginx/conf.d/default.conf

# Copy our nginx config
COPY ./docker/config/assets.local.conf /etc/nginx/conf.d/default.conf

# Copy static assets into nginx html root
COPY ./frontend/dist /usr/share/nginx/html/assets

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]