#!/usr/bin/env php
<?php

declare(strict_types=1);

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

use Application\Main;

const APP_START = "Command";

require_once 'bootstrap.php';
$app = new Main(ROOT, APP_START);
$app->runCommands();